__author__ = "Jia Jia"
__author_email__ = "angersax@sina.com"
__description__ = "gpt cache"
__license__ = "MIT License"
__title__ = "shcache"
__url__ = "https://github.com/ai-shflow/shcache"
__version__ = "1.0.0"
